server:
  port: 8099

spring:
  profiles: test
  application.name: spring-minibase

minibase:
  storage:
    maxMemstoreSize: 16
    flushMaxRetries: 3
    flushInterval: 300
    dataDir: E:\study\hbase\minibase\data
    maxDiskFiles: 10
    maxThreadPoolSize: 5

